# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/SD/trabalho_1_vivado/trabalho_1/trabalho_1.cache/wt [current_project]
set_property parent.project_path E:/SD/trabalho_1_vivado/trabalho_1/trabalho_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib E:/SD/trabalho_1_vivado/trabalho_1/trabalho_1.srcs/sources_1/new/neander.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top neander -part xc7k70tfbv676-1


write_checkpoint -force -noxdef neander.dcp

catch { report_utilization -file neander_utilization_synth.rpt -pb neander_utilization_synth.pb }
